// Terms of Service — a stable, public ToS URL is a submission requirement for
// the Anthropic connector directory. Kept short and honest: a no-account,
// open-source, pay-per-call tool service.
import { ledgerShell, ledgerFooterCompact, esc } from "./ledger-chrome.js";

export function termsPage(baseUrl) {
  const title = "Terms of Service — Agent402";
  const description = "Agent402 terms of service: open-source, pay-per-call web tools. As-is, no warranty, on-chain settlement.";
  const canonical = `${baseUrl}/terms`;

  const extraCss = `
.tm-wrap{max-width:760px;margin:0 auto;padding:56px 30px}
.tm-eyebrow{font-family:var(--font-mono);font-size:13px;color:var(--accent);margin-bottom:18px}
.tm-h1{font-family:var(--font-body);font-weight:800;font-size:58px;line-height:.96;letter-spacing:-.03em;margin:0 0 14px}
.tm-updated{font-family:var(--font-mono);font-size:13px;color:var(--faint);margin:0 0 32px}
.tm-body p,.tm-body li{font-size:15px;line-height:1.55;color:var(--muted)}
.tm-body p{margin:0 0 14px}
.tm-body ul{margin:0 0 18px;padding:0 0 0 22px}
.tm-body li{margin-bottom:8px}
.tm-body h2{font-family:var(--font-body);font-weight:800;font-size:34px;line-height:1;letter-spacing:-.02em;margin:36px 0 14px;color:var(--ink)}
.tm-body a{color:var(--accent);text-decoration:none}
.tm-body a:hover{text-decoration:underline}
.tm-body b,.tm-body strong{color:var(--ink);font-weight:600}
.tm-body code{font-family:var(--font-mono);font-size:13px;background:var(--surface);color:var(--on-dark);padding:2px 7px;border:1.5px solid var(--ink)}
@media(max-width:600px){.tm-h1{font-size:36px !important}}
`;

  const body = `
<div class="tm-wrap">
<div class="tm-eyebrow">$ GET /terms</div>
<h1 class="tm-h1">Terms of Service</h1>
<p class="tm-updated">Agent402 (agent402.tools) — last updated 2026-07-17.</p>

<div class="tm-body">
<p>Agent402 provides web tools that clients — human-operated or autonomous agents — call over HTTP.
By using the service, including programmatically via the x402 payment protocol or the MCP connector,
you agree to these terms. If you operate an agent that uses the service, you are responsible for that
agent's use. You must be at least 18 and able to form a binding contract. The service is
<a href="https://github.com/MikeyPetrillo/Agent402" rel="noopener">open source</a>; these terms cover the hosted instance at agent402.tools.</p>

<h2>The service</h2>
<ul>
  <li><b>Tool catalog:</b> small, deterministic web tools — same input, same output; no large language model runs in that serving path.</li>
  <li><b>AI gateway:</b> the OpenAI-compatible <code>/v1</code> endpoints (chat, embeddings, image generation, speech) and a small number of catalog tools proxy <b>third-party AI models</b> operated by providers such as OpenAI and models served via OpenRouter. Outputs on these paths are generated by those models from the inputs you send.</li>
  <li>No account or signup. Access is by paying per call (USDC/USDG via the x402 protocol) or, on the pure-CPU tools, by solving a proof-of-work challenge. The hosted MCP connector exposes the pure-CPU tools free, rate-limited.</li>
  <li>Provided <b>"as is", without warranty</b> of any kind. We do not guarantee availability, fitness for a particular purpose, or that any tool or generated output will be error-free or accurate.</li>
</ul>

<h2>Acceptable use</h2>
<ul>
  <li>Don't use the service to break the law, infringe others' rights, or attack the service or third parties (e.g. using the URL-fetching tools against targets you don't control).</li>
  <li>Don't attempt to bypass rate limits, payment, or the proof-of-work gate, or to disrupt availability for others.</li>
  <li><b>Generative paths:</b> don't use the AI gateway or any generative tool to create or attempt to create: child sexual abuse material (zero tolerance — we will block the wallet and report as required by law); non-consensual intimate imagery or sexual content depicting real people; content that impersonates a real person to deceive; material that infringes others' intellectual-property rights; or content whose creation or distribution is otherwise illegal in your jurisdiction or ours.</li>
  <li>Traffic through the AI gateway is also subject to the <b>usage policies of the upstream model providers</b> (including OpenAI's usage policies and the terms of OpenRouter and the model operators it serves). Those providers apply their own safety filtering and may refuse requests; their policies apply to your use through us.</li>
  <li>You are responsible for the inputs you send and how you use the outputs.</li>
</ul>

<h2>Generated content</h2>
<p>Outputs from the AI gateway are produced by third-party models from your inputs. We do not review
them, do not claim ownership of them, and do not publish or host them — they are returned to you and,
aside from short-lived caches that make repeated identical calls cheaper, not retained. Generated
content may be inaccurate, incomplete, or unsuitable for your purpose; it is not professional, legal,
financial, or medical advice. Your use of generated content, including any obligation to verify it or
mark it as AI-generated where the law requires, is your responsibility.</p>

<h2>Enforcement</h2>
<p>We may refuse service to, rate-limit, or block any wallet at our discretion, including for violations
of these terms or of upstream provider policies, and may do so without prior notice. To report abuse,
infringement, or illegal content involving this service, email
<a href="mailto:mike@agent402.tools">mike@agent402.tools</a> — reports are reviewed promptly.</p>

<h2>Payments</h2>
<p>Paid calls settle on public blockchains via x402 — USDC on Base, Solana, Polygon, Arbitrum, Monad,
Stellar, or Algorand, and USDG on Robinhood Chain. Micropayments are per-call and,
once settled on-chain, are final and non-refundable except where required by law. You are responsible
for your own wallet and keys; we never receive or hold your private key.</p>

<h2>Availability & changes</h2>
<p>The service may change, be rate-limited, or be discontinued at any time. We may update these terms;
the "last updated" date reflects the current version. Continued use after a change means you accept it.</p>

<h2>Indemnification</h2>
<p>You agree to indemnify and hold harmless Havok Holdings LLC and the service's maintainers and
contributors from claims, damages, and reasonable costs (including legal fees) arising from your use of
the service, the inputs you send, the outputs you generate, or your violation of these terms or of
applicable law.</p>

<h2>Liability</h2>
<p>To the maximum extent permitted by law, Agent402 and its maintainer are not liable for any indirect,
incidental, or consequential damages, or for any losses arising from use of the service, the tools,
generated content, or on-chain payments. Total liability for any claim will not exceed the amount you
paid for the call at issue.</p>

<h2>Operator &amp; contact</h2>
<p>Agent402.Tools is operated by <strong>Havok Holdings LLC</strong>. Contact: <a href="mailto:mike@agent402.tools">mike@agent402.tools</a>,
<a href="https://github.com/MikeyPetrillo/Agent402" rel="noopener">github.com/MikeyPetrillo/Agent402</a>,
or <a href="https://x.com/Agent402Tools" rel="noopener">@Agent402Tools on X</a>.</p>
</div>
</div>
${ledgerFooterCompact()}`;

  return ledgerShell({ title, description, canonical, baseUrl, activePath: "/terms", extraCss, body });
}
